config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :command_events
  # Devise
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }

  # Web app
  root to: "application#home"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  # include Encryptable
  # attr_encrypted :token, :secret, :refresh_token

  belongs_to :user, optional: true
  validates_uniqueness_of :uid, scope: [:provider]
end

app/models/command_event.rb
class CommandEvent < ApplicationRecord
    validates :name, :duration, :client_id, :tuist_version, :swift_version, :macos_version, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Devise
  devise(
    :database_authenticatable,
    :rememberable,
    :validatable,
    :timeoutable,
    :trackable,
    :omniauthable,
    omniauth_providers: %i[github]
  )

  # Associations
  has_many :authorizations, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_raven_context
  protect_from_forgery with: :exception

  def home
  end

  protected
  def restrict_to_development
    head(:bad_request) unless Rails.env.development?
  end

  private
    def set_raven_context
      Raven.user_context(id: session[:current_user_id]) # or anything else in session
      Raven.extra_context(params: params.to_unsafe_h, url: request.url)
    end
end

app/controllers/command_events_controller.rb
# frozen_string_literal: true

class CommandEventsController < ApplicationController
  before_action :set_command_event, only: [:show, :edit, :update, :destroy]

  # Only in development we want to be able to explore the database via a convenient interface. Create is the only API exposed in production
  before_action :restrict_to_development, only: [:index, :show, :new, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, if: :json_request?

  # GET /command_events
  # GET /command_events.json
  def index
    @command_events = CommandEvent.all
  end

  # GET /command_events/10
  # GET /command_events/1.json
  def show
  end

  # GET /command_events/new
  def new
    @command_event = CommandEvent.new
  end

  # GET /command_events/1/edit
  def edit
  end

  # POST /command_events
  # POST /command_events.json
  def create
    @command_event = CommandEvent.new(command_event_params)

    respond_to do |format|
      if @command_event.save
        format.html { redirect_to @command_event, notice: "Command event was successfully created." }
        format.json { render :show, status: :created, location: @command_event }
      else
        format.html { render :new }
        format.json { render json: @command_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /command_events/1
  # PATCH/PUT /command_events/1.json
  def update
    respond_to do |format|
      if @command_event.update(command_event_params)
        format.html { redirect_to @command_event, notice: "Command event was successfully updated." }
        format.json { render :show, status: :ok, location: @command_event }
      else
        format.html { render :edit }
        format.json { render json: @command_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /command_events/1
  # DELETE /command_events/1.json
  def destroy
    @command_event.destroy
    respond_to do |format|
      format.html { redirect_to command_events_url, notice: "Command event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command_event
      @command_event = CommandEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def command_event_params
      params.require(:command_event).permit(
        :name,
        :subcommand,
        :duration,
        :client_id,
        :tuist_version,
        :swift_version,
        :macos_version,
        :machine_hardware_name,
        params: {} # Allow any key inside the params JSON
        )
    end

    def restrict_to_development
      head(:bad_request) unless Rails.env.development?
    end

    def json_request?
      request.format.json?
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = UserCreateService.call(auth: auth_data)

    if @user.persisted?
      sign_in_and_redirect(@user, event: :authentication)
    else
      data = auth_data.except("extra")
      session["devise.oauth.data"] = data
      redirect_to(new_user_registration_url)
    end
  end

  def failure
    redirect_to(root_path)
  end

  def auth_data
    request.env["omniauth.auth"]
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  protected
    def respond_to_on_destroy
      head :no_content
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def show_svg(path)
    File.open("app/assets/images/#{path}", "rb") do |file|
      raw file.read
    end
  end

  TuistGraphColorPalette = ["#6236FF", "#8FBFE0", "#1D8A99", "#0BC9CD", "#14FFF7", "#E2E4F6", "#E7C8DD", "#DBAFC1", "#D8A7B1", "#B6E2D3", "#FAE8E0", "#EF7C8E", "#887BB0", "#85D2D0"]
end

app/helpers/command_events_helper.rb
module CommandEventsHelper
end

app/views/command_events/_form.html.erb
<%= form_with(model: command_event, local: true) do |form| %>
  <% if command_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(command_event.errors.count, "error") %> prohibited this command_event from being saved:</h2>

      <ul>
        <% command_event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :subcommand %>
    <%= form.text_field :subcommand %>
  </div>

  <div class="field">
    <%= form.label :params %>
    <%= form.text_field :params %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :tuist_version %>
    <%= form.text_field :tuist_version %>
  </div>

  <div class="field">
    <%= form.label :swift_version %>
    <%= form.text_field :swift_version %>
  </div>

  <div class="field">
    <%= form.label :macos_version %>
    <%= form.text_field :macos_version %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/command_events/edit.html.erb
<h1>Editing Command Event</h1>

<%= render 'form', command_event: @command_event %>

<%= link_to 'Show', @command_event %> |
<%= link_to 'Back', command_events_path %>

app/views/command_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Command Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subcommand</th>
      <th>Params</th>
      <th>Duration</th>
      <th>Client</th>
      <th>Tuist version</th>
      <th>Swift version</th>
      <th>Macos version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @command_events.each do |command_event| %>
      <tr>
        <td><%= command_event.name %></td>
        <td><%= command_event.subcommand %></td>
        <td><%= command_event.params %></td>
        <td><%= command_event.duration %></td>
        <td><%= command_event.client_id %></td>
        <td><%= command_event.tuist_version %></td>
        <td><%= command_event.swift_version %></td>
        <td><%= command_event.macos_version %></td>
        <td><%= link_to 'Show', command_event %></td>
        <td><%= link_to 'Edit', edit_command_event_path(command_event) %></td>
        <td><%= link_to 'Destroy', command_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command Event', new_command_event_path %>

app/views/command_events/new.html.erb
<h1>New Command Event</h1>

<%= render 'form', command_event: @command_event %>

<%= link_to 'Back', command_events_path %>

app/views/command_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @command_event.name %>
</p>

<p>
  <strong>Subcommand:</strong>
  <%= @command_event.subcommand %>
</p>

<p>
  <strong>Params:</strong>
  <%= @command_event.params %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @command_event.duration %>
</p>

<p>
  <strong>Client:</strong>
  <%= @command_event.client_id %>
</p>

<p>
  <strong>Tuist version:</strong>
  <%= @command_event.tuist_version %>
</p>

<p>
  <strong>Swift version:</strong>
  <%= @command_event.swift_version %>
</p>

<p>
  <strong>Macos version:</strong>
  <%= @command_event.macos_version %>
</p>

<%= link_to 'Edit', edit_command_event_path(@command_event) %> |
<%= link_to 'Back', command_events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuist Stats</title>
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://stats.tuist.io">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Tuist Stats">
    <meta property="og:description" content="Every project generation is a possible merge conflict that didn't happen.">
    <meta property="og:image" content="https://stats.tuist.io/og-image.png">
    
    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="stats.tuist.io">
    <meta property="twitter:url" content="https://stats.tuist.io">
    <meta name="twitter:title" content="Tuist Stats">
    <meta name="twitter:description" content="Every project generation is a possible merge conflict that didn't happen.">
    <meta name="twitter:image" content="https://stats.tuist.io/og-image.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>